version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: sonar-backup-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar_pass
      POSTGRES_DB: sonar_backup
    ports:
      - "5433:5432"
    volumes:
      - sonar_backup_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar -d sonar_backup"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sonar_backup_pg_data:
    driver: local
